// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRhrd6tEtyUENLcDLhIWqQUy_t-QExp8k',
    appId: '1:195391760517:web:23622d71b015ae554ae1ec',
    messagingSenderId: '195391760517',
    projectId: 'carehub-af7ec',
    authDomain: 'carehub-af7ec.firebaseapp.com',
    storageBucket: 'carehub-af7ec.appspot.com',
    measurementId: 'G-03PPNW5TBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCowM7mjk-LtmOYXDR01nwSszpRdZb3-m0',
    appId: '1:195391760517:android:9a80ee93672f92234ae1ec',
    messagingSenderId: '195391760517',
    projectId: 'carehub-af7ec',
    storageBucket: 'carehub-af7ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsa-5ubgyNZwjpCEtjPGoPxwBbEFIbQJc',
    appId: '1:195391760517:ios:f1d2b51642bd05ed4ae1ec',
    messagingSenderId: '195391760517',
    projectId: 'carehub-af7ec',
    storageBucket: 'carehub-af7ec.appspot.com',
    iosClientId: '195391760517-e832ho7dm96178m5nosqrd67fgrjd59v.apps.googleusercontent.com',
    iosBundleId: 'com.example.carehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsa-5ubgyNZwjpCEtjPGoPxwBbEFIbQJc',
    appId: '1:195391760517:ios:f1d2b51642bd05ed4ae1ec',
    messagingSenderId: '195391760517',
    projectId: 'carehub-af7ec',
    storageBucket: 'carehub-af7ec.appspot.com',
    iosClientId: '195391760517-e832ho7dm96178m5nosqrd67fgrjd59v.apps.googleusercontent.com',
    iosBundleId: 'com.example.carehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRhrd6tEtyUENLcDLhIWqQUy_t-QExp8k',
    appId: '1:195391760517:web:da8c3c920141ed614ae1ec',
    messagingSenderId: '195391760517',
    projectId: 'carehub-af7ec',
    authDomain: 'carehub-af7ec.firebaseapp.com',
    storageBucket: 'carehub-af7ec.appspot.com',
    measurementId: 'G-2QBXSJFKQ5',
  );
}
